version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - "4200:4200"
    - "35729:35729"
    volumes:
    - .:/app
    - node-modules:/app/node_modules
volumes:
  node-modules: